version: "3.8"

services:
  sql-db:
    container_name: sql-ecommerce
    image: mysql
    ports:
      - 3317:3306
    restart: always
    environment:
      MYSQL_DATABASE: "ecommerce"
      MYSQL_ROOT_PASSWORD: "admin"