spring:
    datasource:
        url: jdbc:mysql://localhost:3317/ecommerce
        username: root
        password: admin
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        database: mysql
        open-in-view: false
        show-sql: true
        hibernate:
            format_sql: true
            ddl-auto: create-drop
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher

server:
    error:
        include-message: always
        include-stacktrace: on-param
        include-exception: false
